Update check-pr.yml

diff --git a/.github/workflows/check-pr.yml b/.github/workflows/check-pr.yml
--- a/.github/workflows/check-pr.yml
+++ b/.github/workflows/check-pr.yml
@@ -12,13 +12,12 @@ jobs:
         uses: actions/checkout@v2
       - name: Check branch names
         run: |
-          if [ ${{ github.context.payload.sender.type == 'User' }} ]; then
-            if [ ${{ github.head_ref }} != "development" ]; then
-              echo "::error::Pull request must be from the development branch"
-              exit 1
-            fi
-            if [ ${{ github.base_ref }} != "development" ]; then
-              echo "::error::Pull request must be merged into the development branch"
-              exit 1
-            fi
+          if [ ${{ github.head_ref }} != "development" ]; then
+            echo "::error::Pull request must be from the development branch"
+            exit 1
           fi
+          if [ ${{ github.base_ref }} != "development" ]; then
+            echo "::error::Pull request must be merged into the development branch"
+            exit 1
+          fi
+     
